### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by DavidMont** [flipkart-incubator/springy-heads#1]
Error:(23, 13) Failed to resolve: com.flipkart.chatheads:app:0.9.6

what should I put in my build.gradle root?

**Comment by thekirankumar** [comment]
Thanks for pointing out, I had forgotten to push some changes.
Please pull from master again.

**Comment by thekirankumar** [comment]
Thanks for pointing out, I had forgotten to push some changes.
Please pull from master again.
