### ISSUE TITLE
adding EdiText 

### ISSUE THREAD

**Issue by ray-pixar** [flipkart-incubator/springy-heads#10]
could you please consider adding an EdiText to the view. I've tried using FLAG_NOT_FOCUSABLE, but it makes no difference. The Soft Keyboard doesn't pop. Also it ruines the onKey event in MotionCapturingTouchListener.

**Comment by thekirankumar** [comment]
I have pushed some more changes, can you check now ?

**Comment by ray-pixar** [comment]
Great. Thank you.
