### ISSUE TITLE
how to add ViewPager to Chatheads?

### ISSUE THREAD

**Issue by hoangvandan** [flipkart-incubator/springy-heads#15]
can you help me?. how to add ViewPager to Chatheads?

**Comment by hoangvandan** [comment]
or scollview to chatheads

**Comment by thekirankumar** [comment]
Do you mean that you have so many chat heads that they go outside the screen and you want to scroll through them ?
Or do you want to add viewpager into the container which shows up when chat head is maximized ?

**Comment by hoangvandan** [comment]
yes, I so many chat heads and i want to scroll through them.

**Comment by thekirankumar** [comment]
Right now it is not implemented in a way to support scrolling. Pull requests are welcome.

**Comment by thekirankumar** [comment]
No, not supported

**Comment by hoangvandan** [comment]
ok tkanks
