### ISSUE TITLE
iOS Version?

### ISSUE THREAD

**Issue by bintu1234** [flipkart-incubator/springy-heads#6]
Is this possible for ios version in future.

**Comment by rajatgupta26** [comment]
Hi @bintu1234 checkout [FCChatHeads](https://github.com/rajatgupta26/fk-ios-chat-heads).
We've made it available on cocoapods. use `pod "FCCheatHeads"`.

**Comment by thekirankumar** [comment]
Closing issue since @rajatgupta26 has ported the ios version
