### ISSUE TITLE
Setting unread count for chat head functionality missing!

### ISSUE THREAD

**Issue by Byragoni** [flipkart-incubator/springy-heads#7]
Do we have the functionality for setting unread count on the chat head. Looking at the source code, it seems the functionality is not there. Am I right?

In the demo app, though you are showing unread count as 2, that is just part of image. I feel that's a misleading info!

**Comment by thekirankumar** [comment]
The functionality for generating the view for chat head is in a different repo : [circular-drawable](https://github.com/flipkart-incubator/circular-image)
Do check it out. The drawable generated by that library has to be returned in the following method :
```
 public Drawable getChatHeadDrawable(Object key) {
        // this is where you return a drawable for the chat head itself based on the key. Typically you return a circular shape
        // you may want to checkout circular image library https://github.com/flipkart-incubator/circular-image
        return getResources().getDrawable(R.drawable.circular_view);
    }
```

**Comment by thekirankumar** [comment]
I have updated the Readme just in case. Closing the issue.

**Comment by hoangvandan** [comment]
Can you update  scroll through them next time
