### ISSUE TITLE
screen rotation support

### ISSUE THREAD

**Issue by ray-pixar** [flipkart-incubator/springy-heads#9]
Hi
"**run-in-service**" branch doesn't support screen orientation change.

**Comment by thekirankumar** [comment]
Will be fixed in next release

**Comment by thekirankumar** [comment]
Please check the updated commits

**Comment by ray-pixar** [comment]
still not working. if I drag the bubble to the right of screen, after second or third rotation it doesn't stick to the right side any more.

**Comment by thekirankumar** [comment]
Please check my latest commits

**Comment by ray-pixar** [comment]
It works perfectly. Many thanks.

**Comment by thekirankumar** [comment]
No probs.
